# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee4056710f8a9f470df97873c86fe4d5465da88f38e7a11edd77d8f3f70d92f60233972e9016f1e7227f7b478dd9a6d838cc3ef20fb66ecdaf6aa7626967e862

test:
  secret_key_base: 7f2127edbd887d8636e440ba58fd27df4c290afc4e339f9c1ab68def89d7a30e8f80fe49efaf5afa732ae8ccdc2a24f0afd3ccf2ad96a4d8bfd12e147e7fe66e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ee4056710f8a9f470df97873c86fe4d5465da88f38e7a11edd77d8f3f70d92f60233972e9016f1e7227f7b478dd9a6d838cc3ef20fb66ecdaf6aa7626967e862
  #<%= ENV["SECRET_KEY_BASE"] %>
